/**
 * DANGER BOT CONFIGURATION
 * ========================
 * Configurações globais do Danger Bot
 * 
 * IMPORTANTE SOBRE MENSAGENS DO DANGER:
 * 
 * O Danger JS adiciona automaticamente:
 * 1. ":tada: All green. Good on 'ya" quando não há problemas
 * 2. "Generated by Danger" no footer (adicionado pelo platform)
 * 
 * Infelizmente, NÃO É POSSÍVEL remover essas mensagens via código
 * porque elas são adicionadas DEPOIS que o dangerfile termina de executar.
 * 
 * SOLUÇÕES:
 * 1. Para "All green": Sempre adicionar pelo menos uma mensagem/warning para evitar
 * 2. Para footer: O platform (Bitbucket/GitHub) gera isso, não o Danger
 * 
 * WORKAROUND: Adicionar sempre uma mensagem customizada para "ofuscar" o "All green"
 */

/**
 * Adiciona uma mensagem de sucesso customizada em português
 * 
 * Esta é a melhor solução para "substituir" a mensagem "All green" do Danger.
 * Como não podemos removê-la, adicionamos nossa própria mensagem que aparece
 * ANTES dela, tornando a mensagem do Danger menos visível.
 * 
 * @param customMessage Mensagem de sucesso (padrão: mensagem em português)
 */
export function addSuccessMessage(customMessage?: string): void {
  const markdown = (global as any).markdown || (globalThis as any).markdown;
  const results = (global as any).results || (globalThis as any).results;
  
  if (!markdown || !results) return;
  
  // Agendar para rodar no final
  const schedule = (global as any).schedule || (globalThis as any).schedule;
  
  const addMessage = () => {
    // Verificar se há erros/warnings
    const hasIssues = (results.fails && results.fails.length > 0) ||
                     (results.warnings && results.warnings.length > 0);
    
    // Só adicionar mensagem de sucesso se não houver problemas
    if (!hasIssues) {
      const message = customMessage || "✅ **Análise de código concluída!**\n\nNenhum problema encontrado. Código aprovado para merge! 🚀";
      markdown(message);
    }
  };
  
  if (schedule) {
    schedule(addMessage);
  } else {
    addMessage();
  }
}

/**
 * Configuração do Danger Bot
 * 
 * Adiciona uma mensagem de sucesso customizada em português que aparece
 * ANTES da mensagem padrão "All green" do Danger.
 * 
 * NOTA: Não é possível remover a mensagem "All green" do Danger porque
 * ela é adicionada DEPOIS que o dangerfile termina de executar.
 * 
 * @param options Opções de configuração
 * @param options.successMessage Mensagem de sucesso customizada
 * @param options.addCustomSuccess Se true, adiciona mensagem customizada (padrão: true)
 * 
 * @example
 * // Configuração padrão (adiciona mensagem em português)
 * setupDangerConfig();
 * 
 * // Customizar mensagem
 * setupDangerConfig({ 
 *   successMessage: "🎉 Código revisado e aprovado!" 
 * });
 * 
 * // Não adicionar mensagem customizada
 * setupDangerConfig({ 
 *   addCustomSuccess: false 
 * });
 */
export function setupDangerConfig(options?: {
  successMessage?: string;
  addCustomSuccess?: boolean;
}): void {
  const {
    successMessage,
    addCustomSuccess = true
  } = options || {};
  
  if (addCustomSuccess) {
    addSuccessMessage(successMessage);
  }
}



